### ISSUE TITLE
mark todo

### ISSUE THREAD

**Issue by liyatang** [gmfe/react-gm#49]
* [x]  整理 docs @farzer
* [x]  整理 index.js
* [x]  整理 Storage
* [x]  webpack2
* [x]  webpack moment
* [x]  searchfilter 重构 搜索框在下拉列表上
* [x]  检查 PropTypes 的类型，具体到内部，如果是obj
* [x] 表单支持sm md xs lg
* [x] 补充字体图标页面
* [x] 补充浮层的三角标 @fondadam
* [x] Sheet对子元素undefined的兼容 
* [ ] 增加hover tip 组件
* [x] 清理intro

**Comment by farzer** [comment]
我可以先帮忙整理docs

**Comment by liyatang** [comment]
领任务的话就在 任务后面 @自己
